# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= stm32-dfu
MCU ?= STM32F303
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= no
COMMAND_ENABLE ?= no
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= yes
BACKLIGHT_ENABLE ?= no
RGBLIGHT_ENABLE ?= no
BLUETOOTH_ENABLE ?= no
AUDIO_ENABLE ?= no
ENCODER_ENABLE ?= yes
RGB_MATRIX_ENABLE ?= yes
BOOTMAGIC_ENABLE ?= lite
